# Generated by Django 2.2.6 on 2019-11-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PackageRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('repo', models.CharField(max_length=150)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='github.PackageName')),
            ],
        ),
    ]
